<?php

require('../fpdf186/fpdf.php');
include("../db.php");

/* GET FILTER TYPE */
$type = isset($_GET['type']) ? $_GET['type'] : "all";

$where="1";

/* FILTER LOGIC */

if($type=="week" && isset($_GET['start_week']) && isset($_GET['end_week'])){
$sw=$_GET['start_week'];
$ew=$_GET['end_week'];

if($sw <= $ew){
$where="WEEK(o.created_at,1) BETWEEN '$sw' AND '$ew'";
}
}

elseif($type=="month" && isset($_GET['start_month']) && isset($_GET['end_month']) && isset($_GET['year'])){
$sm=$_GET['start_month'];
$em=$_GET['end_month'];
$year=$_GET['year'];

if($sm <= $em){
$where="MONTH(o.created_at) BETWEEN '$sm' AND '$em' AND YEAR(o.created_at)='$year'";
}
}

elseif($type=="quarter" && isset($_GET['quarter'])){
$q=$_GET['quarter'];

if($q==1){ $where="MONTH(o.created_at) BETWEEN 1 AND 3"; }
if($q==2){ $where="MONTH(o.created_at) BETWEEN 4 AND 6"; }
if($q==3){ $where="MONTH(o.created_at) BETWEEN 7 AND 9"; }
if($q==4){ $where="MONTH(o.created_at) BETWEEN 10 AND 12"; }
}

elseif($type=="year" && isset($_GET['start_year']) && isset($_GET['end_year'])){
$sy=$_GET['start_year'];
$ey=$_GET['end_year'];

if($sy <= $ey){
$where="YEAR(o.created_at) BETWEEN '$sy' AND '$ey'";
}
}

/* QUERY */

$query="
SELECT o.*, IFNULL(f.cost_price,0) as cost_price
FROM orders o
LEFT JOIN food_items f ON o.food_name=f.food_name
WHERE $where
";

$result=mysqli_query($conn,$query);

/* PDF START */

$pdf = new FPDF();
$pdf->AddPage();

/* LOGO */
$pdf->Image('../images/logo.png',10,10,25);

/* TITLE */
$pdf->SetFont('Arial','B',18);
$pdf->Cell(0,12,'Profit / Loss Report',0,1,'C');

$pdf->SetFont('Arial','',11);
$pdf->Cell(0,8,"Report Type : ".strtoupper($type),0,1,'C');
$pdf->Cell(0,8,"Generated On : ".date("d-m-Y"),0,1,'C');

$pdf->Ln(5);

/* TABLE HEADER */

$pdf->SetFillColor(255,99,71);
$pdf->SetTextColor(255,255,255);
$pdf->SetFont('Arial','B',11);

$pdf->Cell(40,7,"Food",1,0,'C',true);
$pdf->Cell(25,7,"Sell",1,0,'C',true);
$pdf->Cell(25,7,"Cost",1,0,'C',true);
$pdf->Cell(20,7,"Qty",1,0,'C',true);
$pdf->Cell(30,7,"Profit",1,0,'C',true);
$pdf->Cell(30,7,"Loss",1,1,'C',true);

/* DATA */

$pdf->SetFont('Arial','',10);
$pdf->SetTextColor(0,0,0);

$total_profit = 0;
$total_loss = 0;

while($row=mysqli_fetch_assoc($result)){

$sell = $row['price'];
$cost = $row['cost_price'];
$qty = $row['quantity'];

$profit = ($sell - $cost) * $qty;

$profit_value = 0;
$loss_value = 0;

if($profit >= 0){
$profit_value = $profit;
$total_profit += $profit_value;
}else{
$loss_value = abs($profit);
$total_loss += $loss_value;
}

/* ROW */

$pdf->Cell(40,7,$row['food_name'],1);
$pdf->Cell(25,7,"Rs ".$sell,1);
$pdf->Cell(25,7,"Rs ".$cost,1);
$pdf->Cell(20,7,$qty,1);
$pdf->Cell(30,7,"Rs ".$profit_value,1);
$pdf->Cell(30,7,"Rs ".$loss_value,1);
$pdf->Ln();
}

/* TOTAL */

$pdf->Ln(5);
$pdf->SetFont('Arial','B',12);

$pdf->Cell(95,10,"Total Profit : Rs ".$total_profit,1,0,'C');
$pdf->Cell(95,10,"Total Loss : Rs ".$total_loss,1,1,'C');

$pdf->Ln(5);

/* FOOTER */

$pdf->SetFont('Arial','I',9);
$pdf->Cell(0,10,"Generated by Online Food Ordering System",0,1,'C');

/* DOWNLOAD */

$pdf->Output("D","profit_loss_report.pdf");

?>