<?php
session_start();
if(!isset($_SESSION['admin_id']) || $_SESSION['role'] != 'admin'){
    header("Location: admin_login.php");
    exit();
}

include("../db.php");

/* ================= USERS DELETE ================= */
if(isset($_GET['delete_id'])){
    $id = intval($_GET['delete_id']);
    $stmt = $conn->prepare("DELETE FROM users WHERE id=?");
    $stmt->bind_param("i", $id);
    $stmt->execute();
    header("Location: report.php");
    exit();
}

/* ================= ORDER ACTIONS ================= */
if(isset($_GET['delete_order'])){
    $id=intval($_GET['delete_order']);
    mysqli_query($conn,"DELETE FROM orders WHERE id=$id");
    header("Location: report.php");
    exit();
}

if(isset($_GET['confirm_id'])){
    $id=intval($_GET['confirm_id']);
    mysqli_query($conn,"UPDATE orders SET status='Confirmed' WHERE id=$id");
    header("Location: report.php");
    exit();
}

if(isset($_GET['complete_id'])){
    $id=intval($_GET['complete_id']);
    mysqli_query($conn,"UPDATE orders SET status='Completed' WHERE id=$id");
    header("Location: report.php");
    exit();
}

/* ================= COUNT ================= */
function getCount($conn,$q){
    $r=mysqli_query($conn,$q);
    $d=mysqli_fetch_assoc($r);
    return $d['total'] ?? 0;
}

$totalUsers = getCount($conn,"SELECT COUNT(*) as total FROM users");
$totalOrders = getCount($conn,"SELECT COUNT(*) as total FROM orders");
$pendingOrders = getCount($conn,"SELECT COUNT(*) as total FROM orders WHERE status='Pending'");
$completedOrders = getCount($conn,"SELECT COUNT(*) as total FROM orders WHERE status='Completed'");
$totalFood = getCount($conn,"SELECT COUNT(*) as total FROM food_items");
$totalSales = getCount($conn,"SELECT SUM(total_amount) as total FROM orders WHERE status='Completed'");

/* ================= PDF ================= */
if(isset($_GET['pdf'])){
    require('../fpdf186/fpdf.php');

    $pdf = new FPDF();
    $pdf->AddPage();

    if(file_exists('../images/logo.png')){
        $pdf->Image('../images/logo.png',75,10,60);
    }

    $pdf->Ln(45);

    $pdf->SetFont('Arial','B',18);
    $pdf->Cell(0,10,'Food Ordering System Report',0,1,'C');

    $pdf->SetFont('Arial','',11);
    $pdf->Cell(0,10,'Date: '.date("d-m-Y h:i A"),0,1,'R');

    $pdf->Ln(8);

    $pdf->SetFont('Arial','B',12);
    $pdf->SetFillColor(52,152,219);
    $pdf->SetTextColor(255);

    $pdf->Cell(95,10,'Report Item',1,0,'C',true);
    $pdf->Cell(95,10,'Value',1,1,'C',true);

    $pdf->SetTextColor(0);
    $pdf->SetFont('Arial','',12);

    $pdf->Cell(95,10,'Total Users',1);
    $pdf->Cell(95,10,$totalUsers,1,1);

    $pdf->Cell(95,10,'Total Orders',1);
    $pdf->Cell(95,10,$totalOrders,1,1);

    $pdf->Cell(95,10,'Pending Orders',1);
    $pdf->Cell(95,10,$pendingOrders,1,1);

    $pdf->Cell(95,10,'Completed Orders',1);
    $pdf->Cell(95,10,$completedOrders,1,1);

    $pdf->Cell(95,10,'Total Food Items',1);
    $pdf->Cell(95,10,$totalFood,1,1);

    $pdf->Cell(95,10,'Total Sales (₹)',1);
    $pdf->Cell(95,10,$totalSales,1,1);

    $pdf->Ln(10);
    $pdf->SetFont('Arial','I',10);
    $pdf->Cell(0,10,'Generated by Admin Panel',0,1,'C');

    $pdf->Output();
    exit();
}
?>

<!DOCTYPE html>
<html>
<head>
<title>Advanced Report</title>

<style>
body{font-family:Segoe UI;background:#eef2f7;margin:0}
header{background:linear-gradient(45deg,#2c3e50,#3498db);color:#fff;padding:20px;text-align:center}
.container{width:90%;margin:auto}
.cards{display:flex;gap:20px;margin:20px 0}
.card{flex:1;background:#fff;padding:20px;border-radius:10px;box-shadow:0 5px 15px rgba(0,0,0,0.1);text-align:center}
.box{background:#fff;padding:20px;border-radius:10px;margin-bottom:20px}
table{width:100%;border-collapse:collapse}
th,td{padding:10px;border-bottom:1px solid #ddd}
th{background:#3498db;color:#fff}
.btn{padding:6px 10px;color:#fff;border-radius:5px;text-decoration:none}
.edit{background:#27ae60}
.delete{background:#e74c3c}
.download{background:#2ecc71}
.dropdown-box{text-align:center;margin:25px 0}
.dropdown-box select{padding:10px 20px;width:260px;border-radius:8px;border:1px solid #ccc}
</style>
</head>

<body onload="showSection('users')">

<header><h2>📊 Advanced Report Dashboard</h2></header>

<div class="container">

<a href="?pdf=1" class="btn download">Download PDF</a>

<div class="dropdown-box">
<select onchange="showSection(this.value)">
<option value="">Select Report</option>
<option value="users">Users</option>
<option value="orders">Orders</option>
<option value="food">Food Items</option>
<option value="contact">Contact</option>
</select>
</div>

<div class="cards">
<div class="card">Users<br><?php echo $totalUsers; ?></div>
<div class="card">Orders<br><?php echo $totalOrders; ?></div>
<div class="card">Sales<br>₹<?php echo $totalSales; ?></div>
</div>

<!-- USERS -->
<div class="box" id="users">
<h3>Users</h3>
<table>
<tr><th>ID</th><th>Name</th><th>Email</th><th>Action</th></tr>
<?php
$res=mysqli_query($conn,"SELECT * FROM users");
while($row=mysqli_fetch_assoc($res)){
?>
<tr>
<td><?php echo $row['id']; ?></td>
<td><?php echo htmlspecialchars($row['name']); ?></td>
<td><?php echo htmlspecialchars($row['email']); ?></td>
<td>
<a class="btn delete" href="?delete_id=<?php echo $row['id']; ?>">Delete</a>
</td>
</tr>
<?php } ?>
</table>
</div>

<!-- ORDERS -->
<div class="box" id="orders" style="display:none;">

<h3>🟡 Pending Orders</h3>
<table>
<tr><th>ID</th><th>User</th><th>Amount</th><th>Status</th><th>Date</th><th>Action</th></tr>
<?php
$q=mysqli_query($conn,"SELECT * FROM orders WHERE status='Pending'");
while($o=mysqli_fetch_assoc($q)){
?>
<tr>
<td><?php echo $o['id']; ?></td>
<td><?php echo $o['user_id']; ?></td>
<td>₹<?php echo $o['total_amount']; ?></td>
<td><?php echo $o['status']; ?></td>
<td><?php echo $o['created_at']; ?></td>
<td>
<a class="btn edit" href="?confirm_id=<?php echo $o['id']; ?>">Confirm</a>
<a class="btn delete" href="?delete_order=<?php echo $o['id']; ?>">Delete</a>
</td>
</tr>
<?php } ?>
</table>

<h3>🔵 Confirmed Orders</h3>
<table>
<tr><th>ID</th><th>User</th><th>Amount</th><th>Status</th><th>Date</th><th>Action</th></tr>
<?php
$q=mysqli_query($conn,"SELECT * FROM orders WHERE status='Confirmed'");
while($o=mysqli_fetch_assoc($q)){
?>
<tr>
<td><?php echo $o['id']; ?></td>
<td><?php echo $o['user_id']; ?></td>
<td>₹<?php echo $o['total_amount']; ?></td>
<td><?php echo $o['status']; ?></td>
<td><?php echo $o['created_at']; ?></td>
<td>
<a class="btn edit" href="?complete_id=<?php echo $o['id']; ?>">Complete</a>
<a class="btn delete" href="?delete_order=<?php echo $o['id']; ?>">Delete</a>
</td>
</tr>
<?php } ?>
</table>

<h3>🟢 Completed Orders</h3>
<table>
<tr><th>ID</th><th>User</th><th>Amount</th><th>Status</th><th>Date</th></tr>
<?php
$q=mysqli_query($conn,"SELECT * FROM orders WHERE status='Completed'");
while($o=mysqli_fetch_assoc($q)){
?>
<tr>
<td><?php echo $o['id']; ?></td>
<td><?php echo $o['user_id']; ?></td>
<td>₹<?php echo $o['total_amount']; ?></td>
<td><?php echo $o['status']; ?></td>
<td><?php echo $o['created_at']; ?></td>
</tr>
<?php } ?>
</table>

</div>

<!-- FOOD -->
<div class="box" id="food" style="display:none;">
<h3>Food Items</h3>
<table>
<tr><th>ID</th><th>Name</th><th>Price</th></tr>
<?php
$f=mysqli_query($conn,"SELECT * FROM food_items");
while($d=mysqli_fetch_assoc($f)){
?>
<tr>
<td><?php echo $d['id']; ?></td>
<td><?php echo htmlspecialchars($d['food_name']); ?></td>
<td>₹<?php echo $d['price']; ?></td>
</tr>
<?php } ?>
</table>
</div>

<!-- CONTACT -->
<div class="box" id="contact" style="display:none;">
<h3>Feedback form</h3>
<table>
<tr><th>ID</th><th>Name</th><th>Email</th><th>Message</th></tr>
<?php
$c=mysqli_query($conn,"SELECT * FROM contact_messages");
while($row=mysqli_fetch_assoc($c)){
?>
<tr>
<td><?php echo $row['id']; ?></td>
<td><?php echo htmlspecialchars($row['name']); ?></td>
<td><?php echo htmlspecialchars($row['email']); ?></td>
<td><?php echo htmlspecialchars($row['message']); ?></td>
</tr>
<?php } ?>
</table>
</div>

</div>

<script>
function showSection(section){
    document.getElementById("users").style.display="none";
    document.getElementById("orders").style.display="none";
    document.getElementById("food").style.display="none";
    document.getElementById("contact").style.display="none";
    document.getElementById(section).style.display="block";
}
</script>

</body>
</html>